---
- name: reboot server into rescue image
  hosts: servers
  connection: local
  vars_files:
  - secrets.yml
  roles:
  - role: hetzner-boot-rescue

- name: install ubuntu 19.04 minimal
  hosts: servers
  vars_files:
  - secrets.yml
  roles:
  - role: hetzner-install-ubuntu-19.04
  
- name: install docker
  hosts: servers
  vars_files:
  - secrets.yml
  roles:
  - role: install-docker

- name: final reboot
  hosts: servers
  vars_files:
  - secrets.yml
  roles:
  - role: reboot
